### ISSUE TITLE
Personalise game

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#10]
As a **user** I can **add my name** so that **I can see my personal game score on the leadership board**

Tasks:
- [x] add <input> element to homepage for text input
- [x] add element to display user's name in gameplay

Acceptance Criteria:
- [x] user can enter their name before playing
- [x] user can see their name during gameplay
- [ ] user can see their name on the leaderboard if they achieve a high score
