### ISSUE TITLE
Increase score

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#11]
As a **user** I can **collect a range of tokens when playing** so that **I can increase my score**

Tasks:
- [x] add food and collectable tokens to maps
- [x] create score function to increase when colliding with token
- [x] create collision function with player
- [x] append new score to gameplay screen

Acceptance Criteria:
- [x] user can see their score changing as they collect tokens
