### ISSUE TITLE
See score changing

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#13]
As a **user** I can **see my score increasing/decreasing as I play** so that **I can understand how well I'm playing**

Tasks:
- [x] JS code to increase/decrease score when making contact with tokens
- [x] feed score to gameplay HTML when it changes

Acceptance Criteria:
- [x] user can see their current score at all times during game play
