### ISSUE TITLE
See current highest score

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#14]
As a **user** I can **see the current game high score** so that **I know how many points I have to get to beat it**

Tasks:
- [ ] store high score in file
- [ ] display high score on homepage, leaderboard and game play

Acceptance Criteria:
- [ ] user can see how many points the highest score is in several parts of the site
