### ISSUE TITLE
Start on basic health

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#15]
As a **user** I can **see my starting health is in the middle of the range** so that **I'm aware how many health levels I can gain/lose**

Tasks:
- [ ] add style to health range to show current health
- [ ] starting health is smily face

Acceptance Criteria:
- [ ] user can see that they start on the middle health state
