### ISSUE TITLE
See health ranges

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#16]
As a **user** I can **see the health range represented by different emojis** so that **I'm aware which emojis represent good/bad health and where my health is in relation**

Tasks:
- [x] add range of health emojis to rules
- [x] highlight/border current health in range
- [x] change emojiman avatar to current health range emoji

Acceptance Criteria:
- [x] users understand the range of health emojiman can have
- [x] users are always aware which health they are on
