### ISSUE TITLE
Lose health

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#18]
As a **user** I can **see health draining tokens** so that **I can avoid these tokens to maintain good health**

Task:
- [x] append enemies to the map
- [x] add enemies list in maps files
- [x] add enemies emoji list above game play

Acceptance Criteria:
- [x] user is aware which emojis will sap their health
- [x] user can see their health reducing upon collision with enemy
