### ISSUE TITLE
Different themes

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#21]
As a **user** I can **see the characters/tokens/map change in appearance between levels** so that **the game play is new and interesting between each level**

Tasks:
- [x] create JSON file for different map layouts
- [x] create JSON file to represent different themes ie with tokens/baddies
- [x] add different background for each theme

Acceptance Criteria:
- [x] user can see the gameplay style and theme change between levels
- [x] user is always aware what different tokens mean in relation to that level
