### ISSUE TITLE
Level introduction

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#22]
As a **user** I can **see a brief story introduction to each level** so that **I understand who the goodies/baddies are, how to complete the level, which tokens I'm collecting etc**

Tasks:
- [ ] create HTML & CSS for central div to congratulate for previous level completion and tell story of next level
- [ ] add tokens/goodies/baddies emojis and explanation
- [ ] add JS to pop this div up upon level completion
- [ ] add button for "Launch next level"

Acceptance Criteria:
- [ ] user is aware when they've finished a level
- [ ] user understands the next level theme
- [ ] user can see which emojis to collect and avoid
