### ISSUE TITLE
Understand loss of progress

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#26]
As a **user** I can **see a warning of exiting the game** so that **I understand the consequences of exiting the game early**

Tasks:
- [ ] add modal to pop up during game play if game is exited
- [ ] add warning about loss of progress

Acceptance Criteria:
- [ ] user is aware of the consequences of exiting the game
