### ISSUE TITLE
Recognise game

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#7]
As a **user** I can **see a preview of the game on the homepage** so that **I know this is a Pacman-style game**

Tasks:
- [x] create homepage
- [x] add screenshot of game in play as banner image
- [x] add description of game
- [x] add game rules

Acceptance Criteria:
- [x] users are immediately aware of the type of game they are playing when landing on the website homepage
