### ISSUE TITLE
Find game rules

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#8]
As a **user** I can **see the game rules on the homepage** so that **I can understand how to play the game**

Tasks:
- [x] add game rules for user to scroll down
- [x] add 'Game Rules' button which jumps to this section

Acceptance Criteria:
- [x] users can see how to play the game
- [x] the game rules capture all aspects of the game
