### ISSUE TITLE
Launch game

### ISSUE THREAD

**Issue by MojosBeans100** [seanyoung247/emoji-man#9]
As a **user** I can **see a 'Launch Game' button on the homepage** so that **I know how to start playing**

Tasks:
- [ ] add 'Launch Game' button to homepage
- [ ] add JS function to pull up first level for this button
- [x] create game div to display gameplay, hints about tokens etc

Acceptance Criteria:
- [ ] user can see the button upon landing on homepage
- [ ] user can launch the game without having to navigate to a separate page

**It was decided to launch the game upon visiting the webpage**
